version: '3'

services:
  proxy:
    image: "jwilder/nginx-proxy"
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "web_certs:/etc/nginx/certs:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
    networks:
      - proxy-tier
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  ssl:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    container_name: "letsencrypt-nginx-proxy-companion"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "web_certs:/etc/nginx/certs:rw"
      - "vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 120s

volumes:
  web_certs:
  vhost:
  nginx_html:

networks:
  proxy-tier: